#!/bin/bash
echo -ne "Installation Begins.."
for i in 1 2 3 4 5
do
  echo -ne "."
  sleep 0.5
done
echo -e "\n"
echo "Checking For a System Update"
read -p 'Do you want to Cancel(Y/N): ' answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo "Skipping Update..."
else
    apt update && apt upgrade -y
fi
echo -e "\n"

echo "Checking for python3 and pip3"
apt install python3
apt install python3-pip3
echo -e "\n"

echo "Installing Required Python Package"
pip3 install -r ./requirements.txt

echo -e "\n"
echo "Installation Completed"
