#!/bin/bash
echo -ne "Installation Begins.."
for i in 1 2 3 4 5
do
  echo -ne "."
  sleep 0.5
done
echo -e "\n"
echo "Checking For a System Update"
read -p 'Do you want to Cancel(Y/N): ' answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    echo "Skipping Update..."
else
    apt update && apt upgrade -y
fi
echo -e "\n"

echo "Checking for python3 and pip3"
apt install python3
apt install python3-pip
echo -e "\n"

echo "Installing Required Python Package"
pip3 install -r ./requirements.txt

echo -e "\n"
echo "link below for geckodriver Download and install"
echo "https://github.com/mozilla/geckodriver/releases"
echo -e "\n"
read -p 'If you are using linux-x64then proceed with Y if not then N: ' answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
	wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
	tar -xvzf geckodriver*
	chmod +x geckodriver
	export PATH=$PATH:/path-to-extracted-file/.
fi
echo -e "\n"
echo "Installation Completed"
